# Generated by Django 4.1.7 on 2023-05-02 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streak',
            fields=[
                ('idStreak', models.BigAutoField(primary_key=True, serialize=False)),
                ('streakStartDate', models.DateTimeField()),
                ('streakLastCheckOffDate', models.DateTimeField(null=True)),
                ('streakNextDate', models.DateTimeField()),
                ('streakLastDate', models.DateTimeField(null=True)),
                ('streakCheckOff', models.IntegerField(default=0)),
                ('streakStatus', models.BooleanField(default=True)),
                ('idHbitFk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streak', to='habitApp.habit')),
            ],
        ),
    ]
